name: scrolling_buttons_bar
description: buttons with an scrolling and animation on selection.
version: 0.0.1
homepage: https://github.com/mucahitbircan/scrolling_buttons_bar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
