name: scrolling_buttons_bar
description: A new Flutter package project.
version: 0.0.1
author: Mucahit Bircan
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
